create table if not exists public.hidden_products (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  created_at timestamptz not null default now()
);

alter table public.hidden_products enable row level security;

drop policy if exists "hidden_products_select_public" on public.hidden_products;
create policy "hidden_products_select_public"
on public.hidden_products
for select
to anon, authenticated
using (true);

drop policy if exists "hidden_products_insert_admin" on public.hidden_products;
create policy "hidden_products_insert_admin"
on public.hidden_products
for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'maksym.huk@gmail.com');

