create table if not exists public.custom_products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  sport text not null,
  category text not null,
  image text not null,
  price numeric not null check (price > 0),
  old_price numeric null check (old_price is null or old_price > 0),
  rating numeric not null default 4.5 check (rating >= 0 and rating <= 5),
  reviews integer not null default 0 check (reviews >= 0),
  badge text null check (badge is null or badge in ('Хит', 'Новинка', 'Скидка')),
  created_at timestamptz not null default now()
);

alter table public.custom_products enable row level security;

drop policy if exists "custom_products_select_public" on public.custom_products;
create policy "custom_products_select_public"
on public.custom_products
for select
to anon, authenticated
using (true);

drop policy if exists "custom_products_insert_admin" on public.custom_products;
create policy "custom_products_insert_admin"
on public.custom_products
for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'maksym.huk@gmail.com');

drop policy if exists "custom_products_delete_admin" on public.custom_products;
create policy "custom_products_delete_admin"
on public.custom_products
for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'maksym.huk@gmail.com');

